export {
  WORKSPACE_CAPABILITIES,
  WorkspaceService,
  type WorkspaceServiceOptions,
} from "./service.js";
export {
  WorkspaceCoreError,
  WorkspaceRemoteError,
  asWorkspaceCoreError,
  type WorkspaceCoreErrorCode,
} from "./errors.js";
export {
  DEFAULT_WORKSPACE_LIMITS,
  createWorkspaceManifest,
  hashManifestEntries,
  readStableScannedFile,
  scanWorkspace,
  sha256,
} from "./manifest.js";
export {
  assertNoPortablePathCollisions,
  canonicalizeManifestEntries,
  normalizeRegistrationPath,
  normalizeWorkspacePath,
  portablePathKey,
} from "./path-policy.js";
export { diffWorkspaceManifests, hasWorkspaceChanges } from "./diff.js";
export {
  createUnmaterializedState,
  deriveLocalReplicaStatus,
  markConflict,
  markLeaseOrBaseInvalid,
  withActiveLease,
  withoutActiveLease,
  withoutRevision,
} from "./state-machine.js";
export { materializeWorkspace, recoverMaterialization } from "./materialization.js";
export {
  syncWorkspace,
  useLocalWorkspace,
  useServerWorkspace,
  type WorkspaceSyncResult,
  type WorkspaceSyncSecrets,
} from "./sync.js";
export type {
  ClockPort,
  ConfigurationStatus,
  CredentialKind,
  CredentialPort,
  CredentialReference,
  DiagnosticCheck,
  DiagnosticCheckStatus,
  DirectoryEntry,
  DoctorResult,
  FileSnapshot,
  LocalLeaseSummary,
  LocalReplicaStatus,
  LocalWorkspaceState,
  MaterializationFilePort,
  MaterializationJournal,
  MaterializationOperation,
  MaterializationRequest,
  MaterializationResult,
  PlatformAdapter,
  PlatformInformation,
  PreservedConflict,
  RemoteDeviceAccessToken,
  RemotePairingCliStatus,
  RemotePairingCreated,
  RemotePairingCredential,
  RemotePairingStatus,
  RemoteWorkspaceLease,
  RemoteWorkspaceLeaseGrant,
  RemoteWorkspaceMetadata,
  RemoteWorkspaceVersion,
  RenamedWorkspaceFile,
  ScannedWorkspaceFile,
  WorkspaceApiPort,
  WorkspaceCapability,
  WorkspaceConnectionStatus,
  WorkspaceControlPort,
  WorkspaceDiff,
  WorkspaceFilePort,
  WorkspaceLimits,
  WorkspaceManifest,
  WorkspaceManifestEntry,
  WorkspaceObjectReaderPort,
  WorkspaceRegistration,
  WorkspaceRegistry,
  WorkspaceRegistryPort,
  WorkspaceScanResult,
  WorkspaceStatus,
} from "./types.js";
